# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bio-polyploid-tools"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ricardo Ramirez-Gonzalez"]
  s.date = "2013-09-13"
  s.description = "Repository of tools developed in TGAC and Crop Genetics in JIC to work with polyploid wheat"
  s.email = "ricardo.ramirez-gonzalez@tgac.ac.uk"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README",
    "Rakefile",
    "VERSION",
    "lib/bio/BFRTools.rb",
    "lib/bio/BIOExtensions.rb",
    "lib/bio/PolyploidTools/ChromosomeArm.rb",
    "lib/bio/PolyploidTools/ExonContainer.rb",
    "lib/bio/PolyploidTools/PrimerRegion.rb",
    "lib/bio/PolyploidTools/SNP.rb",
    "lib/bio/PolyploidTools/SNPSequence.rb",
    "lib/bio/SAMToolsExtensions.rb",
    "lib/bio/db/exonerate.rb",
    "lib/bio/db/fasta.rb",
    "lib/bio/db/primer3.rb",
    "lib/bioruby-polyploid-tools.rb",
    "test/data/BS00068396_51.fa",
    "test/data/BS00068396_51_contigs.aln",
    "test/data/BS00068396_51_contigs.dnd",
    "test/data/BS00068396_51_contigs.fa",
    "test/data/BS00068396_51_exonerate.tab",
    "test/data/BS00068396_51_genes.txt",
    "test/data/short_primer_design_test.csv",
    "test/test_exonearate.rb",
    "test/test_snp_parsing.rb"
  ]
  s.homepage = "http://github.com/homonecloco/bioruby-polyploid-tools"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Tool to work with polyploids, NGS and molecular biology"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

